kind: pipeline
type: docker
steps:
- name: github-action
  image: plugins/github-actions
  settings:
    uses: .github/workflows/publish
    with:
        who-to-greet: Mona the Octocat
    env:
        hello: world