kind: pipeline
type: docker
steps:
- name: publish-to-cloudflare
  image: gauravsh0112/cfpages-react
  settings:
    uses: .github/workflows/publish
    with:
        who-to-greet: Mona the Octocat
    env:
        hello: world